export const searchSite = '/alarmsiteinfo/getAlarmsiteinfoByID'
export const searchCity = '/alarmsiteinfo/getAllCityLongitudeLatitudes'
export const getAllsite = '/alarmsiteinfo/getAllAlarmsiteinfo'
export const getAnalysis = '/alarmsiteinfo/getAnalysis'
export const getDistrictNum = '/alarmsiteinfo/getDistrictNum'

export const searchSiteSHU = '/evacuationBase/getEvaBaseInfoByField'
export const searchCitySHU = '/evacuationBase/getAllCityEvaBase'
export const getAllsiteSHU = '/evacuationBase/getAllEvaBaseInfo'
export const getAnalysisSHU = '/evacuationBase/getEvacuationAnalysis'
export const getDistrictNumSHU = '/evacuationBase/getEvacuationNum'